CREATE TABLE CMS AS
    SELECT * FROM '*.parquet';

CREATE TABLE DIM_LOCATIONS AS
    SELECT * FROM 'DIM_LOCATIONS.CSV';

CREATE TABLE DIM_MEDICATIONS AS
    SELECT * FROM 'DIM_MEDICATIONS.CSV';

CREATE TABLE DIM_PROVIDERS AS
    SELECT * FROM 'DIM_PROVIDERS.CSV';